// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: canTerminationConfig.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createCanTerminationConfig = `-- name: CreateCanTerminationConfig :one
insert into can_termination_confs (can_1_terminated, can_2_terminated, can_3_terminated,can_4_terminated)
VALUES($1,$2,$3,$4)
on conflict (can_1_terminated, can_2_terminated, can_3_terminated, can_4_terminated) do nothing
returning id, can_1_terminated, can_3_terminated, can_2_terminated, can_4_terminated, created_at, updated_at, is_deleted
`

type CreateCanTerminationConfigParams struct {
	Can1Terminated sql.NullBool `json:"can_1_terminated"`
	Can2Terminated sql.NullBool `json:"can_2_terminated"`
	Can3Terminated sql.NullBool `json:"can_3_terminated"`
	Can4Terminated sql.NullBool `json:"can_4_terminated"`
}

func (q *Queries) CreateCanTerminationConfig(ctx context.Context, arg CreateCanTerminationConfigParams) (CanTerminationConf, error) {
	row := q.db.QueryRowContext(ctx, createCanTerminationConfig,
		arg.Can1Terminated,
		arg.Can2Terminated,
		arg.Can3Terminated,
		arg.Can4Terminated,
	)
	var i CanTerminationConf
	err := row.Scan(
		&i.ID,
		&i.Can1Terminated,
		&i.Can3Terminated,
		&i.Can2Terminated,
		&i.Can4Terminated,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsDeleted,
	)
	return i, err
}

const getAllCanTerminationConfig = `-- name: GetAllCanTerminationConfig :many
select id, can_1_terminated, can_2_terminated, can_3_terminated, can_4_terminated
from can_termination_confs
`

type GetAllCanTerminationConfigRow struct {
	ID             uuid.UUID    `json:"id"`
	Can1Terminated sql.NullBool `json:"can_1_terminated"`
	Can2Terminated sql.NullBool `json:"can_2_terminated"`
	Can3Terminated sql.NullBool `json:"can_3_terminated"`
	Can4Terminated sql.NullBool `json:"can_4_terminated"`
}

func (q *Queries) GetAllCanTerminationConfig(ctx context.Context) ([]GetAllCanTerminationConfigRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllCanTerminationConfig)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllCanTerminationConfigRow
	for rows.Next() {
		var i GetAllCanTerminationConfigRow
		if err := rows.Scan(
			&i.ID,
			&i.Can1Terminated,
			&i.Can2Terminated,
			&i.Can3Terminated,
			&i.Can4Terminated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTerminationConfigIdByCanTerminated = `-- name: GetTerminationConfigIdByCanTerminated :one
select id
from can_termination_confs
where can_1_terminated = $1
  and can_2_terminated = $2
  and can_3_terminated = $3
  and can_4_terminated = $4
`

type GetTerminationConfigIdByCanTerminatedParams struct {
	Can1Terminated sql.NullBool `json:"can_1_terminated"`
	Can2Terminated sql.NullBool `json:"can_2_terminated"`
	Can3Terminated sql.NullBool `json:"can_3_terminated"`
	Can4Terminated sql.NullBool `json:"can_4_terminated"`
}

func (q *Queries) GetTerminationConfigIdByCanTerminated(ctx context.Context, arg GetTerminationConfigIdByCanTerminatedParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, getTerminationConfigIdByCanTerminated,
		arg.Can1Terminated,
		arg.Can2Terminated,
		arg.Can3Terminated,
		arg.Can4Terminated,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
