// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: canTerminationConfig.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createTerminationConfig = `-- name: CreateTerminationConfig :one
insert into can_termination_confs (can_1_terminated, can_2_terminated, can_3_terminated,can_4_terminated)
VALUES($1,$2,$3,$4)
on conflict (can_1_terminated, can_2_terminated, can_3_terminated, can_4_terminated) do nothing
returning id
`

type CreateTerminationConfigParams struct {
	Can1Terminated sql.NullBool `json:"can_1_terminated"`
	Can2Terminated sql.NullBool `json:"can_2_terminated"`
	Can3Terminated sql.NullBool `json:"can_3_terminated"`
	Can4Terminated sql.NullBool `json:"can_4_terminated"`
}

func (q *Queries) CreateTerminationConfig(ctx context.Context, arg CreateTerminationConfigParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, createTerminationConfig,
		arg.Can1Terminated,
		arg.Can2Terminated,
		arg.Can3Terminated,
		arg.Can4Terminated,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getAllTerminationConfig = `-- name: GetAllTerminationConfig :many
select id, can_1_terminated, can_3_terminated, can_2_terminated, can_4_terminated
from can_termination_confs
`

type GetAllTerminationConfigRow struct {
	ID             uuid.UUID    `json:"id"`
	Can1Terminated sql.NullBool `json:"can_1_terminated"`
	Can3Terminated sql.NullBool `json:"can_3_terminated"`
	Can2Terminated sql.NullBool `json:"can_2_terminated"`
	Can4Terminated sql.NullBool `json:"can_4_terminated"`
}

func (q *Queries) GetAllTerminationConfig(ctx context.Context) ([]GetAllTerminationConfigRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllTerminationConfig)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllTerminationConfigRow
	for rows.Next() {
		var i GetAllTerminationConfigRow
		if err := rows.Scan(
			&i.ID,
			&i.Can1Terminated,
			&i.Can3Terminated,
			&i.Can2Terminated,
			&i.Can4Terminated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTerminationConfigIdByCanTerminated = `-- name: GetTerminationConfigIdByCanTerminated :one
select id
from can_termination_confs
where can_1_terminated = $1
  and can_2_terminated = $2
  and can_3_terminated = $3
  and can_4_terminated = $4
`

type GetTerminationConfigIdByCanTerminatedParams struct {
	Can1Terminated sql.NullBool `json:"can_1_terminated"`
	Can2Terminated sql.NullBool `json:"can_2_terminated"`
	Can3Terminated sql.NullBool `json:"can_3_terminated"`
	Can4Terminated sql.NullBool `json:"can_4_terminated"`
}

func (q *Queries) GetTerminationConfigIdByCanTerminated(ctx context.Context, arg GetTerminationConfigIdByCanTerminatedParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, getTerminationConfigIdByCanTerminated,
		arg.Can1Terminated,
		arg.Can2Terminated,
		arg.Can3Terminated,
		arg.Can4Terminated,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
