// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: controllerPcbHwVersions.sql

package database

import (
	"context"
)

const createControllerPcbHwVersion = `-- name: CreateControllerPcbHwVersion :one
BEGIN
`

type CreateControllerPcbHwVersionRow struct {
}

func (q *Queries) CreateControllerPcbHwVersion(ctx context.Context) (CreateControllerPcbHwVersionRow, error) {
	row := q.db.QueryRowContext(ctx, createControllerPcbHwVersion)
	var i CreateControllerPcbHwVersionRow
	err := row.Scan()
	return i, err
}

const getAllControllerPcbHwVersions = `-- name: GetAllControllerPcbHwVersions :many
SELECT id, version_number, revision, created_at, updated_at, is_deleted
FROM controller_pcb_hw_versions
`

func (q *Queries) GetAllControllerPcbHwVersions(ctx context.Context) ([]ControllerPcbHwVersion, error) {
	rows, err := q.db.QueryContext(ctx, getAllControllerPcbHwVersions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ControllerPcbHwVersion
	for rows.Next() {
		var i ControllerPcbHwVersion
		if err := rows.Scan(
			&i.ID,
			&i.VersionNumber,
			&i.Revision,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsDeleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
