// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: controllers.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const createController = `-- name: CreateController :one
INSERT INTO CONTROLLERS (CONTROLLER_TYPES_ID,
                         PROJECTS_ID,
                         DESCRIPTION,
                         controllers_pcb_hw_versions_id,
                         SERIAL_NUMBER,
                         MANUFACTURERS_ID,
                         MAC_ADDRESS,
                         SIM_NUMBER,
                         MINI_PCIE_MODULES_ID,
                         m2_modules_types_id,
                         display_adapters_id,
                         ARTICLE_NUMBER,
                         info_QR_CODE,
                         CAN_TERMINATION_CONFS_ID,
                         USB,
                         serial,
                         manufacturer_qr_code,
                         ORDER_ID)
VALUES ($1,
        $2,
        $3,
        $4,
        $5,
        $6,
        $7,
        $8,
        $9,
        $10,
        $11,
        $12,
        $13,
        $14,
        $15,
        $16,
        $17,
        $18)
returning
    id, controller_types_id, projects_id, description, controllers_pcb_hw_versions_id, pcb_version_number, serial_number, manufacturers_id, assembly_date, mac_address, sim_number, mini_pcie_modules_id, m2_modules_types_id, display_adapters_id, article_number, info_qr_code, can_termination_confs_id, usb, serial, manufacturer_qr_code, order_id, created_at, updated_at, is_deleted
`

type CreateControllerParams struct {
	ControllerTypesID          uuid.NullUUID  `json:"controller_types_id"`
	ProjectsID                 uuid.NullUUID  `json:"projects_id"`
	Description                sql.NullString `json:"description"`
	ControllersPcbHwVersionsID uuid.NullUUID  `json:"controllers_pcb_hw_versions_id"`
	SerialNumber               sql.NullString `json:"serial_number"`
	ManufacturersID            uuid.NullUUID  `json:"manufacturers_id"`
	MacAddress                 sql.NullString `json:"mac_address"`
	SimNumber                  sql.NullString `json:"sim_number"`
	MiniPcieModulesID          uuid.NullUUID  `json:"mini_pcie_modules_id"`
	M2ModulesTypesID           uuid.NullUUID  `json:"m2_modules_types_id"`
	DisplayAdaptersID          uuid.NullUUID  `json:"display_adapters_id"`
	ArticleNumber              sql.NullString `json:"article_number"`
	InfoQrCode                 sql.NullString `json:"info_qr_code"`
	CanTerminationConfsID      uuid.NullUUID  `json:"can_termination_confs_id"`
	Usb                        sql.NullBool   `json:"usb"`
	Serial                     sql.NullBool   `json:"serial"`
	ManufacturerQrCode         sql.NullString `json:"manufacturer_qr_code"`
	OrderID                    uuid.NullUUID  `json:"order_id"`
}

func (q *Queries) CreateController(ctx context.Context, arg CreateControllerParams) (Controller, error) {
	row := q.db.QueryRowContext(ctx, createController,
		arg.ControllerTypesID,
		arg.ProjectsID,
		arg.Description,
		arg.ControllersPcbHwVersionsID,
		arg.SerialNumber,
		arg.ManufacturersID,
		arg.MacAddress,
		arg.SimNumber,
		arg.MiniPcieModulesID,
		arg.M2ModulesTypesID,
		arg.DisplayAdaptersID,
		arg.ArticleNumber,
		arg.InfoQrCode,
		arg.CanTerminationConfsID,
		arg.Usb,
		arg.Serial,
		arg.ManufacturerQrCode,
		arg.OrderID,
	)
	var i Controller
	err := row.Scan(
		&i.ID,
		&i.ControllerTypesID,
		&i.ProjectsID,
		&i.Description,
		&i.ControllersPcbHwVersionsID,
		&i.PcbVersionNumber,
		&i.SerialNumber,
		&i.ManufacturersID,
		&i.AssemblyDate,
		&i.MacAddress,
		&i.SimNumber,
		&i.MiniPcieModulesID,
		&i.M2ModulesTypesID,
		&i.DisplayAdaptersID,
		&i.ArticleNumber,
		&i.InfoQrCode,
		&i.CanTerminationConfsID,
		&i.Usb,
		&i.Serial,
		&i.ManufacturerQrCode,
		&i.OrderID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsDeleted,
	)
	return i, err
}

const createJoinControllerSlotToIoModule = `-- name: CreateJoinControllerSlotToIoModule :one
INSERT INTO controller_slot (controllers_id, io_modules_id, slot_number)
VALUES ($1, $2, $3)
returning
    id, controllers_id, io_modules_id, slot_number, is_deleted
`

type CreateJoinControllerSlotToIoModuleParams struct {
	ControllersID uuid.NullUUID `json:"controllers_id"`
	IoModulesID   uuid.NullUUID `json:"io_modules_id"`
	SlotNumber    sql.NullInt32 `json:"slot_number"`
}

func (q *Queries) CreateJoinControllerSlotToIoModule(ctx context.Context, arg CreateJoinControllerSlotToIoModuleParams) (ControllerSlot, error) {
	row := q.db.QueryRowContext(ctx, createJoinControllerSlotToIoModule, arg.ControllersID, arg.IoModulesID, arg.SlotNumber)
	var i ControllerSlot
	err := row.Scan(
		&i.ID,
		&i.ControllersID,
		&i.IoModulesID,
		&i.SlotNumber,
		&i.IsDeleted,
	)
	return i, err
}

const getALLControllerTypes = `-- name: GetALLControllerTypes :many
SELECT id,
       controller_types.name,
       controller_types.io_module_slot_amount
FROM controller_types
`

type GetALLControllerTypesRow struct {
	ID                 uuid.UUID      `json:"id"`
	Name               sql.NullString `json:"name"`
	IoModuleSlotAmount sql.NullInt32  `json:"io_module_slot_amount"`
}

func (q *Queries) GetALLControllerTypes(ctx context.Context) ([]GetALLControllerTypesRow, error) {
	rows, err := q.db.QueryContext(ctx, getALLControllerTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetALLControllerTypesRow
	for rows.Next() {
		var i GetALLControllerTypesRow
		if err := rows.Scan(&i.ID, &i.Name, &i.IoModuleSlotAmount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllControllers = `-- name: GetAllControllers :many
SELECT c.id,
       ct.name                                      AS type_name,
       ct.io_module_slot_amount                     AS io_module_socket_amount,
       p.name                                       AS project_name,
       c.description,
       concat(pcbv.version_number, pcbrev.revision) AS pcb_hw_version,
       c.pcb_version_number,
       c.serial_number                              as serial_number,
       m.name                                       AS manufacturer_name,
       c.assembly_date,
       c.mac_address,
       c.sim_number,
       enc.serial_number                            as enclosure_serial_number,
       encman.name                                  as enclosure_manufacturer,
       mpt.name                                     AS mini_pcie_modules_name,
       mpt.module_type_number                       as mini_pcie_module_type_number,
       mpcie.serial_number                          AS mini_pcie_serial_number,
       m2t.name                                     AS m2_module_name,
       m2t.module_type_number                       AS m2_module_type_number,
       ldb.manufacturer_qr_code                     as led_board_qr_code,
       da.display_adapters_type_name                as display_type,
       da.manufacturer_qr_code                      as display_manufacturer_qr_code,
       c.article_number,
       c.info_qr_code                               as info_qr_code,
       ctc.can_1_terminated,
       ctc.can_2_terminated,
       ctc.can_3_terminated,
       ctc.can_4_terminated,
       c.usb,
       c.serial,
       c.manufacturer_qr_code                       as manufacturer_qr_code,
       c.order_id,
       c.created_at,
       c.updated_at,
       c.is_deleted,
       ct.slot_pinout_json
FROM controllers c
         LEFT JOIN controller_types ct ON c.controller_types_id = ct.id
         LEFT JOIN projects p ON c.projects_id = p.id
         LEFT JOIN controller_pcb_hw_versions pcbv ON c.controllers_pcb_hw_versions_id = pcbv.id
         LEFT JOIN manufacturers m ON c.manufacturers_id = m.id
         left join enclosure enc on c.id = enc.controller_id
         left join manufacturers encman on enc.manufacturers_id = encman.id
         LEFT JOIN mini_pcie_modules mpcie ON c.mini_pcie_modules_id = mpcie.id
         LEFT JOIN m2_modules_types m2t ON c.m2_modules_types_id = m2t.id
         left join display_adapters da on c.display_adapters_id = da.id
         LEFT JOIN can_termination_confs ctc ON c.can_termination_confs_id = ctc.id
         LEFT JOIN controller_pcb_hw_versions_rev pcbrev ON pcbv.revision = pcbrev.revision
         LEFT JOIN mini_pcie_modules_type mpt ON mpcie.mini_pcie_modules_type_id = mpt.id
         left join led_daughter_board ldb on c.id = ldb.controllers_id
`

type GetAllControllersRow struct {
	ID                        uuid.UUID             `json:"id"`
	TypeName                  sql.NullString        `json:"type_name"`
	IoModuleSocketAmount      sql.NullInt32         `json:"io_module_socket_amount"`
	ProjectName               sql.NullString        `json:"project_name"`
	Description               sql.NullString        `json:"description"`
	PcbHwVersion              interface{}           `json:"pcb_hw_version"`
	PcbVersionNumber          sql.NullInt32         `json:"pcb_version_number"`
	SerialNumber              sql.NullString        `json:"serial_number"`
	ManufacturerName          sql.NullString        `json:"manufacturer_name"`
	AssemblyDate              sql.NullTime          `json:"assembly_date"`
	MacAddress                sql.NullString        `json:"mac_address"`
	SimNumber                 sql.NullString        `json:"sim_number"`
	EnclosureSerialNumber     sql.NullString        `json:"enclosure_serial_number"`
	EnclosureManufacturer     sql.NullString        `json:"enclosure_manufacturer"`
	MiniPcieModulesName       sql.NullString        `json:"mini_pcie_modules_name"`
	MiniPcieModuleTypeNumber  sql.NullInt32         `json:"mini_pcie_module_type_number"`
	MiniPcieSerialNumber      sql.NullString        `json:"mini_pcie_serial_number"`
	M2ModuleName              sql.NullString        `json:"m2_module_name"`
	M2ModuleTypeNumber        sql.NullInt32         `json:"m2_module_type_number"`
	LedBoardQrCode            sql.NullString        `json:"led_board_qr_code"`
	DisplayType               sql.NullString        `json:"display_type"`
	DisplayManufacturerQrCode sql.NullString        `json:"display_manufacturer_qr_code"`
	ArticleNumber             sql.NullString        `json:"article_number"`
	InfoQrCode                sql.NullString        `json:"info_qr_code"`
	Can1Terminated            sql.NullBool          `json:"can_1_terminated"`
	Can2Terminated            sql.NullBool          `json:"can_2_terminated"`
	Can3Terminated            sql.NullBool          `json:"can_3_terminated"`
	Can4Terminated            sql.NullBool          `json:"can_4_terminated"`
	Usb                       sql.NullBool          `json:"usb"`
	Serial                    sql.NullBool          `json:"serial"`
	ManufacturerQrCode        sql.NullString        `json:"manufacturer_qr_code"`
	OrderID                   uuid.NullUUID         `json:"order_id"`
	CreatedAt                 sql.NullTime          `json:"created_at"`
	UpdatedAt                 sql.NullTime          `json:"updated_at"`
	IsDeleted                 sql.NullBool          `json:"is_deleted"`
	SlotPinoutJson            pqtype.NullRawMessage `json:"slot_pinout_json"`
}

func (q *Queries) GetAllControllers(ctx context.Context) ([]GetAllControllersRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllControllers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllControllersRow
	for rows.Next() {
		var i GetAllControllersRow
		if err := rows.Scan(
			&i.ID,
			&i.TypeName,
			&i.IoModuleSocketAmount,
			&i.ProjectName,
			&i.Description,
			&i.PcbHwVersion,
			&i.PcbVersionNumber,
			&i.SerialNumber,
			&i.ManufacturerName,
			&i.AssemblyDate,
			&i.MacAddress,
			&i.SimNumber,
			&i.EnclosureSerialNumber,
			&i.EnclosureManufacturer,
			&i.MiniPcieModulesName,
			&i.MiniPcieModuleTypeNumber,
			&i.MiniPcieSerialNumber,
			&i.M2ModuleName,
			&i.M2ModuleTypeNumber,
			&i.LedBoardQrCode,
			&i.DisplayType,
			&i.DisplayManufacturerQrCode,
			&i.ArticleNumber,
			&i.InfoQrCode,
			&i.Can1Terminated,
			&i.Can2Terminated,
			&i.Can3Terminated,
			&i.Can4Terminated,
			&i.Usb,
			&i.Serial,
			&i.ManufacturerQrCode,
			&i.OrderID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsDeleted,
			&i.SlotPinoutJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllControllersPcbHwVersions = `-- name: GetAllControllersPcbHwVersions :many
select id,
       version_number,
       revision
from controller_pcb_hw_versions
`

type GetAllControllersPcbHwVersionsRow struct {
	ID            uuid.UUID      `json:"id"`
	VersionNumber sql.NullString `json:"version_number"`
	Revision      sql.NullString `json:"revision"`
}

func (q *Queries) GetAllControllersPcbHwVersions(ctx context.Context) ([]GetAllControllersPcbHwVersionsRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllControllersPcbHwVersions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllControllersPcbHwVersionsRow
	for rows.Next() {
		var i GetAllControllersPcbHwVersionsRow
		if err := rows.Scan(&i.ID, &i.VersionNumber, &i.Revision); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getControllerById = `-- name: GetControllerById :one
SELECT c.id,
       ct.name                                      AS type_name,
       ct.io_module_slot_amount                     AS io_module_socket_amount,
       p.name                                       AS project_name,
       c.description,
       concat(pcbv.version_number, pcbrev.revision) AS pcb_hw_version,
       c.pcb_version_number,
       c.serial_number                              as serial_number,
       m.name                                       AS manufacturer_name,
       c.assembly_date,
       c.mac_address,
       c.sim_number,
       enc.serial_number                            as enclosure_serial_number,
       encman.name                                  as enclosure_manufacturer,
       mpt.name                                     AS mini_pcie_modules_name,
       mpt.module_type_number                       as mini_pcie_module_type_number,
       mpcie.serial_number                          AS mini_pcie_serial_number,
       m2t.name                                     AS m2_module_name,
       m2t.module_type_number                       AS m2_module_type_number,
       ldb.manufacturer_qr_code                     as led_board_qr_code,
       da.display_adapters_type_name                as display_type,
       da.manufacturer_qr_code                      as display_manufacturer_qr_code,
       c.article_number,
       c.info_qr_code                               as info_qr_code,
       ctc.can_1_terminated,
       ctc.can_2_terminated,
       ctc.can_3_terminated,
       ctc.can_4_terminated,
       c.usb,
       c.serial,
       c.manufacturer_qr_code                       as manufacturer_qr_code,
       c.order_id,
       c.created_at,
       c.updated_at,
       c.is_deleted,
       ct.slot_pinout_json
FROM controllers c
         LEFT JOIN controller_types ct ON c.controller_types_id = ct.id
         LEFT JOIN projects p ON c.projects_id = p.id
         LEFT JOIN controller_pcb_hw_versions pcbv ON c.controllers_pcb_hw_versions_id = pcbv.id
         LEFT JOIN manufacturers m ON c.manufacturers_id = m.id
         left join enclosure enc on c.id = enc.controller_id
         left join manufacturers encman on enc.manufacturers_id = encman.id
         LEFT JOIN mini_pcie_modules mpcie ON c.mini_pcie_modules_id = mpcie.id
         LEFT JOIN m2_modules_types m2t ON c.m2_modules_types_id = m2t.id
         left join display_adapters da on c.display_adapters_id = da.id
         LEFT JOIN can_termination_confs ctc ON c.can_termination_confs_id = ctc.id
         LEFT JOIN controller_pcb_hw_versions_rev pcbrev ON pcbv.revision = pcbrev.revision
         LEFT JOIN mini_pcie_modules_type mpt ON mpcie.mini_pcie_modules_type_id = mpt.id
         left join led_daughter_board ldb on c.id = ldb.controllers_id
WHERE c.id = $1
`

type GetControllerByIdRow struct {
	ID                        uuid.UUID             `json:"id"`
	TypeName                  sql.NullString        `json:"type_name"`
	IoModuleSocketAmount      sql.NullInt32         `json:"io_module_socket_amount"`
	ProjectName               sql.NullString        `json:"project_name"`
	Description               sql.NullString        `json:"description"`
	PcbHwVersion              interface{}           `json:"pcb_hw_version"`
	PcbVersionNumber          sql.NullInt32         `json:"pcb_version_number"`
	SerialNumber              sql.NullString        `json:"serial_number"`
	ManufacturerName          sql.NullString        `json:"manufacturer_name"`
	AssemblyDate              sql.NullTime          `json:"assembly_date"`
	MacAddress                sql.NullString        `json:"mac_address"`
	SimNumber                 sql.NullString        `json:"sim_number"`
	EnclosureSerialNumber     sql.NullString        `json:"enclosure_serial_number"`
	EnclosureManufacturer     sql.NullString        `json:"enclosure_manufacturer"`
	MiniPcieModulesName       sql.NullString        `json:"mini_pcie_modules_name"`
	MiniPcieModuleTypeNumber  sql.NullInt32         `json:"mini_pcie_module_type_number"`
	MiniPcieSerialNumber      sql.NullString        `json:"mini_pcie_serial_number"`
	M2ModuleName              sql.NullString        `json:"m2_module_name"`
	M2ModuleTypeNumber        sql.NullInt32         `json:"m2_module_type_number"`
	LedBoardQrCode            sql.NullString        `json:"led_board_qr_code"`
	DisplayType               sql.NullString        `json:"display_type"`
	DisplayManufacturerQrCode sql.NullString        `json:"display_manufacturer_qr_code"`
	ArticleNumber             sql.NullString        `json:"article_number"`
	InfoQrCode                sql.NullString        `json:"info_qr_code"`
	Can1Terminated            sql.NullBool          `json:"can_1_terminated"`
	Can2Terminated            sql.NullBool          `json:"can_2_terminated"`
	Can3Terminated            sql.NullBool          `json:"can_3_terminated"`
	Can4Terminated            sql.NullBool          `json:"can_4_terminated"`
	Usb                       sql.NullBool          `json:"usb"`
	Serial                    sql.NullBool          `json:"serial"`
	ManufacturerQrCode        sql.NullString        `json:"manufacturer_qr_code"`
	OrderID                   uuid.NullUUID         `json:"order_id"`
	CreatedAt                 sql.NullTime          `json:"created_at"`
	UpdatedAt                 sql.NullTime          `json:"updated_at"`
	IsDeleted                 sql.NullBool          `json:"is_deleted"`
	SlotPinoutJson            pqtype.NullRawMessage `json:"slot_pinout_json"`
}

func (q *Queries) GetControllerById(ctx context.Context, id uuid.UUID) (GetControllerByIdRow, error) {
	row := q.db.QueryRowContext(ctx, getControllerById, id)
	var i GetControllerByIdRow
	err := row.Scan(
		&i.ID,
		&i.TypeName,
		&i.IoModuleSocketAmount,
		&i.ProjectName,
		&i.Description,
		&i.PcbHwVersion,
		&i.PcbVersionNumber,
		&i.SerialNumber,
		&i.ManufacturerName,
		&i.AssemblyDate,
		&i.MacAddress,
		&i.SimNumber,
		&i.EnclosureSerialNumber,
		&i.EnclosureManufacturer,
		&i.MiniPcieModulesName,
		&i.MiniPcieModuleTypeNumber,
		&i.MiniPcieSerialNumber,
		&i.M2ModuleName,
		&i.M2ModuleTypeNumber,
		&i.LedBoardQrCode,
		&i.DisplayType,
		&i.DisplayManufacturerQrCode,
		&i.ArticleNumber,
		&i.InfoQrCode,
		&i.Can1Terminated,
		&i.Can2Terminated,
		&i.Can3Terminated,
		&i.Can4Terminated,
		&i.Usb,
		&i.Serial,
		&i.ManufacturerQrCode,
		&i.OrderID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsDeleted,
		&i.SlotPinoutJson,
	)
	return i, err
}

const getControllerTypesPinout = `-- name: GetControllerTypesPinout :one
select slot_pinout_json
from controller_types
where id = $1
`

func (q *Queries) GetControllerTypesPinout(ctx context.Context, id uuid.UUID) (pqtype.NullRawMessage, error) {
	row := q.db.QueryRowContext(ctx, getControllerTypesPinout, id)
	var slot_pinout_json pqtype.NullRawMessage
	err := row.Scan(&slot_pinout_json)
	return slot_pinout_json, err
}
