// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: customer.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const getAllCustomers = `-- name: GetAllCustomers :many
select id, customers.name from customers
`

type GetAllCustomersRow struct {
	ID   uuid.UUID      `json:"id"`
	Name sql.NullString `json:"name"`
}

func (q *Queries) GetAllCustomers(ctx context.Context) ([]GetAllCustomersRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllCustomers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllCustomersRow
	for rows.Next() {
		var i GetAllCustomersRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllCustomersWithProjects = `-- name: GetAllCustomersWithProjects :many
select c.id, c.name, pj.name
from customers c
left join customer_projects_junction cpj on c.id = cpj.customers_id
left join projects pj on cpj.projects_id = pj.id
`

type GetAllCustomersWithProjectsRow struct {
	ID     uuid.UUID      `json:"id"`
	Name   sql.NullString `json:"name"`
	Name_2 sql.NullString `json:"name_2"`
}

func (q *Queries) GetAllCustomersWithProjects(ctx context.Context) ([]GetAllCustomersWithProjectsRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllCustomersWithProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllCustomersWithProjectsRow
	for rows.Next() {
		var i GetAllCustomersWithProjectsRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Name_2); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCustomerWithProjects = `-- name: GetCustomerWithProjects :many
select c.id, c.name, pj.name
from customers c
left join customer_projects_junction cpj on c.id = cpj.customers_id
left join projects pj on cpj.projects_id = pj.id
where c.id = $1
`

type GetCustomerWithProjectsRow struct {
	ID     uuid.UUID      `json:"id"`
	Name   sql.NullString `json:"name"`
	Name_2 sql.NullString `json:"name_2"`
}

func (q *Queries) GetCustomerWithProjects(ctx context.Context, id uuid.UUID) ([]GetCustomerWithProjectsRow, error) {
	rows, err := q.db.QueryContext(ctx, getCustomerWithProjects, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCustomerWithProjectsRow
	for rows.Next() {
		var i GetCustomerWithProjectsRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Name_2); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
