// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: display.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createDisplayAdapter = `-- name: CreateDisplayAdapter :one
INSERT INTO display_adapters (display_adapters_type_name, manufacturer_qr_code)
VALUES ($1, $2)
returning id, display_adapters_type_name, manufacturer_qr_code, created_at, updated_at, is_deleted
`

type CreateDisplayAdapterParams struct {
	DisplayAdaptersTypeName sql.NullString `json:"display_adapters_type_name"`
	ManufacturerQrCode      sql.NullString `json:"manufacturer_qr_code"`
}

func (q *Queries) CreateDisplayAdapter(ctx context.Context, arg CreateDisplayAdapterParams) (DisplayAdapter, error) {
	row := q.db.QueryRowContext(ctx, createDisplayAdapter, arg.DisplayAdaptersTypeName, arg.ManufacturerQrCode)
	var i DisplayAdapter
	err := row.Scan(
		&i.ID,
		&i.DisplayAdaptersTypeName,
		&i.ManufacturerQrCode,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsDeleted,
	)
	return i, err
}

const createDisplayType = `-- name: CreateDisplayType :one
insert into display_adapters_type (name)
values ($1)
returning name, created_at, updated_at, is_deleted
`

func (q *Queries) CreateDisplayType(ctx context.Context, name string) (DisplayAdaptersType, error) {
	row := q.db.QueryRowContext(ctx, createDisplayType, name)
	var i DisplayAdaptersType
	err := row.Scan(
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsDeleted,
	)
	return i, err
}

const getAllDisplayAdapters = `-- name: GetAllDisplayAdapters :many
select id, display_adapters_type_name, manufacturer_qr_code
from display_adapters
`

type GetAllDisplayAdaptersRow struct {
	ID                      uuid.UUID      `json:"id"`
	DisplayAdaptersTypeName sql.NullString `json:"display_adapters_type_name"`
	ManufacturerQrCode      sql.NullString `json:"manufacturer_qr_code"`
}

func (q *Queries) GetAllDisplayAdapters(ctx context.Context) ([]GetAllDisplayAdaptersRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllDisplayAdapters)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllDisplayAdaptersRow
	for rows.Next() {
		var i GetAllDisplayAdaptersRow
		if err := rows.Scan(&i.ID, &i.DisplayAdaptersTypeName, &i.ManufacturerQrCode); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllDisplayTypes = `-- name: GetAllDisplayTypes :many
select display_adapters_type.name as name
from display_adapters_type
`

func (q *Queries) GetAllDisplayTypes(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getAllDisplayTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
