// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: encloser.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createEncloser = `-- name: CreateEncloser :one
insert into enclosure (controller_id,
                       serial_number,
                       controller_types_id,
                       manufacturers_id)
values ($1, $2, $3, $4)
on conflict (serial_number) do nothing
returning
    id
`

type CreateEncloserParams struct {
	ControllerID      uuid.NullUUID  `json:"controller_id"`
	SerialNumber      sql.NullString `json:"serial_number"`
	ControllerTypesID uuid.NullUUID  `json:"controller_types_id"`
	ManufacturersID   uuid.NullUUID  `json:"manufacturers_id"`
}

func (q *Queries) CreateEncloser(ctx context.Context, arg CreateEncloserParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, createEncloser,
		arg.ControllerID,
		arg.SerialNumber,
		arg.ControllerTypesID,
		arg.ManufacturersID,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getEncloserBySN = `-- name: GetEncloserBySN :one
select id,
       controller_id,
       serial_number,
       controller_types_id,
       manufacturers_id
from enclosure
where serial_number = $1
`

func (q *Queries) GetEncloserBySN(ctx context.Context, serialNumber sql.NullString) (Enclosure, error) {
	row := q.db.QueryRowContext(ctx, getEncloserBySN, serialNumber)
	var i Enclosure
	err := row.Scan(
		&i.ID,
		&i.ControllerID,
		&i.SerialNumber,
		&i.ControllerTypesID,
		&i.ManufacturersID,
	)
	return i, err
}

const getEncloserId = `-- name: GetEncloserId :one
select id,
       controller_id,
       serial_number,
       controller_types_id,
       manufacturers_id
from enclosure
where id = $1
`

func (q *Queries) GetEncloserId(ctx context.Context, id uuid.UUID) (Enclosure, error) {
	row := q.db.QueryRowContext(ctx, getEncloserId, id)
	var i Enclosure
	err := row.Scan(
		&i.ID,
		&i.ControllerID,
		&i.SerialNumber,
		&i.ControllerTypesID,
		&i.ManufacturersID,
	)
	return i, err
}
