// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: ledBoard.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createLedBoard = `-- name: CreateLedBoard :one
insert into led_daughter_board (manufacturer_qr_code, controllers_id)
values ($1,$2)
on conflict (manufacturer_qr_code) do nothing
returning id, manufacturer_qr_code, controllers_id, created_at, updated_at, is_deleted
`

type CreateLedBoardParams struct {
	ManufacturerQrCode sql.NullString `json:"manufacturer_qr_code"`
	ControllersID      uuid.NullUUID  `json:"controllers_id"`
}

func (q *Queries) CreateLedBoard(ctx context.Context, arg CreateLedBoardParams) (LedDaughterBoard, error) {
	row := q.db.QueryRowContext(ctx, createLedBoard, arg.ManufacturerQrCode, arg.ControllersID)
	var i LedDaughterBoard
	err := row.Scan(
		&i.ID,
		&i.ManufacturerQrCode,
		&i.ControllersID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsDeleted,
	)
	return i, err
}

const getLedBoardByQR = `-- name: GetLedBoardByQR :one
select id, manufacturer_qr_code, controllers_id
from led_daughter_board
where manufacturer_qr_code = $1
`

type GetLedBoardByQRRow struct {
	ID                 uuid.UUID      `json:"id"`
	ManufacturerQrCode sql.NullString `json:"manufacturer_qr_code"`
	ControllersID      uuid.NullUUID  `json:"controllers_id"`
}

func (q *Queries) GetLedBoardByQR(ctx context.Context, manufacturerQrCode sql.NullString) (GetLedBoardByQRRow, error) {
	row := q.db.QueryRowContext(ctx, getLedBoardByQR, manufacturerQrCode)
	var i GetLedBoardByQRRow
	err := row.Scan(&i.ID, &i.ManufacturerQrCode, &i.ControllersID)
	return i, err
}
