// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: m2Modules.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createM2Module = `-- name: CreateM2Module :one
INSERT INTO m2_modules_types ("name", module_type_number)
VALUES ($1, $2)
returning id, name, module_type_number, created_at, updated_at, is_deleted
`

type CreateM2ModuleParams struct {
	Name             sql.NullString `json:"name"`
	ModuleTypeNumber sql.NullInt32  `json:"module_type_number"`
}

func (q *Queries) CreateM2Module(ctx context.Context, arg CreateM2ModuleParams) (M2ModulesType, error) {
	row := q.db.QueryRowContext(ctx, createM2Module, arg.Name, arg.ModuleTypeNumber)
	var i M2ModulesType
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ModuleTypeNumber,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsDeleted,
	)
	return i, err
}

const getAllM2Modules = `-- name: GetAllM2Modules :many
SELECT id, name, module_type_number, created_at, updated_at, is_deleted
FROM m2_modules_types
`

func (q *Queries) GetAllM2Modules(ctx context.Context) ([]M2ModulesType, error) {
	rows, err := q.db.QueryContext(ctx, getAllM2Modules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []M2ModulesType
	for rows.Next() {
		var i M2ModulesType
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ModuleTypeNumber,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsDeleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllM2ModulesTypes = `-- name: GetAllM2ModulesTypes :many
select id, name, module_type_number
from m2_modules_types
`

type GetAllM2ModulesTypesRow struct {
	ID               uuid.UUID      `json:"id"`
	Name             sql.NullString `json:"name"`
	ModuleTypeNumber sql.NullInt32  `json:"module_type_number"`
}

func (q *Queries) GetAllM2ModulesTypes(ctx context.Context) ([]GetAllM2ModulesTypesRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllM2ModulesTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllM2ModulesTypesRow
	for rows.Next() {
		var i GetAllM2ModulesTypesRow
		if err := rows.Scan(&i.ID, &i.Name, &i.ModuleTypeNumber); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
