// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: m2Modules.sql

package database

import (
	"context"
)

const getAllM2Modules = `-- name: GetAllM2Modules :many
SELECT id, name, module_type_number, created_at, updated_at, is_deleted
FROM m2_modules_types
`

func (q *Queries) GetAllM2Modules(ctx context.Context) ([]M2ModulesType, error) {
	rows, err := q.db.QueryContext(ctx, getAllM2Modules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []M2ModulesType
	for rows.Next() {
		var i M2ModulesType
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ModuleTypeNumber,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsDeleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
