// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: manufacturers.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createManufacturer = `-- name: CreateManufacturer :one
INSERT INTO manufacturers (name)
VALUES ($1)
RETURNING id, name, created_at, updated_at, is_deleted
`

func (q *Queries) CreateManufacturer(ctx context.Context, name sql.NullString) (Manufacturer, error) {
	row := q.db.QueryRowContext(ctx, createManufacturer, name)
	var i Manufacturer
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsDeleted,
	)
	return i, err
}

const getAllManufacturers = `-- name: GetAllManufacturers :many
SELECT id, name
FROM manufacturers
`

type GetAllManufacturersRow struct {
	ID   uuid.UUID      `json:"id"`
	Name sql.NullString `json:"name"`
}

func (q *Queries) GetAllManufacturers(ctx context.Context) ([]GetAllManufacturersRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllManufacturers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllManufacturersRow
	for rows.Next() {
		var i GetAllManufacturersRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getManufacturerById = `-- name: GetManufacturerById :one
SELECT id, name, created_at, updated_at, is_deleted
FROM manufacturers
WHERE id = $1
`

func (q *Queries) GetManufacturerById(ctx context.Context, id uuid.UUID) (Manufacturer, error) {
	row := q.db.QueryRowContext(ctx, getManufacturerById, id)
	var i Manufacturer
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsDeleted,
	)
	return i, err
}
