// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: miniPCIeModules.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createMiniPCIeModule = `-- name: CreateMiniPCIeModule :one
INSERT INTO mini_pcie_modules (mini_pcie_modules_type_id, serial_number)
VALUES ($1, $2)
RETURNING id, mini_pcie_modules_type_id, serial_number, created_at, updated_at, is_deleted
`

type CreateMiniPCIeModuleParams struct {
	MiniPcieModulesTypeID uuid.NullUUID  `json:"mini_pcie_modules_type_id"`
	SerialNumber          sql.NullString `json:"serial_number"`
}

func (q *Queries) CreateMiniPCIeModule(ctx context.Context, arg CreateMiniPCIeModuleParams) (MiniPcieModule, error) {
	row := q.db.QueryRowContext(ctx, createMiniPCIeModule, arg.MiniPcieModulesTypeID, arg.SerialNumber)
	var i MiniPcieModule
	err := row.Scan(
		&i.ID,
		&i.MiniPcieModulesTypeID,
		&i.SerialNumber,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsDeleted,
	)
	return i, err
}

const getAllMiniPCIeModules = `-- name: GetAllMiniPCIeModules :many
SELECT mpt.name as name,
       m.id, m.mini_pcie_modules_type_id, m.serial_number, m.created_at, m.updated_at, m.is_deleted
FROM mini_pcie_modules m
         LEFT JOIN mini_pcie_modules_type mpt ON mpt.id = m.mini_pcie_modules_type_id
`

type GetAllMiniPCIeModulesRow struct {
	Name                  sql.NullString `json:"name"`
	ID                    uuid.UUID      `json:"id"`
	MiniPcieModulesTypeID uuid.NullUUID  `json:"mini_pcie_modules_type_id"`
	SerialNumber          sql.NullString `json:"serial_number"`
	CreatedAt             sql.NullTime   `json:"created_at"`
	UpdatedAt             sql.NullTime   `json:"updated_at"`
	IsDeleted             sql.NullBool   `json:"is_deleted"`
}

func (q *Queries) GetAllMiniPCIeModules(ctx context.Context) ([]GetAllMiniPCIeModulesRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllMiniPCIeModules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllMiniPCIeModulesRow
	for rows.Next() {
		var i GetAllMiniPCIeModulesRow
		if err := rows.Scan(
			&i.Name,
			&i.ID,
			&i.MiniPcieModulesTypeID,
			&i.SerialNumber,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsDeleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllMiniPCIeModulesType = `-- name: GetAllMiniPCIeModulesType :many
SELECT id, name, module_type_number
FROM mini_pcie_modules_type
`

type GetAllMiniPCIeModulesTypeRow struct {
	ID               uuid.UUID      `json:"id"`
	Name             sql.NullString `json:"name"`
	ModuleTypeNumber sql.NullInt32  `json:"module_type_number"`
}

func (q *Queries) GetAllMiniPCIeModulesType(ctx context.Context) ([]GetAllMiniPCIeModulesTypeRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllMiniPCIeModulesType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllMiniPCIeModulesTypeRow
	for rows.Next() {
		var i GetAllMiniPCIeModulesTypeRow
		if err := rows.Scan(&i.ID, &i.Name, &i.ModuleTypeNumber); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMiniPCIeModuleById = `-- name: GetMiniPCIeModuleById :one
SELECT mpt.name as name,
       m.id, m.mini_pcie_modules_type_id, m.serial_number, m.created_at, m.updated_at, m.is_deleted
FROM mini_pcie_modules m
         LEFT JOIN mini_pcie_modules_type mpt ON mpt.id = m.mini_pcie_modules_type_id
WHERE m.id = $1
`

type GetMiniPCIeModuleByIdRow struct {
	Name                  sql.NullString `json:"name"`
	ID                    uuid.UUID      `json:"id"`
	MiniPcieModulesTypeID uuid.NullUUID  `json:"mini_pcie_modules_type_id"`
	SerialNumber          sql.NullString `json:"serial_number"`
	CreatedAt             sql.NullTime   `json:"created_at"`
	UpdatedAt             sql.NullTime   `json:"updated_at"`
	IsDeleted             sql.NullBool   `json:"is_deleted"`
}

func (q *Queries) GetMiniPCIeModuleById(ctx context.Context, id uuid.UUID) (GetMiniPCIeModuleByIdRow, error) {
	row := q.db.QueryRowContext(ctx, getMiniPCIeModuleById, id)
	var i GetMiniPCIeModuleByIdRow
	err := row.Scan(
		&i.Name,
		&i.ID,
		&i.MiniPcieModulesTypeID,
		&i.SerialNumber,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsDeleted,
	)
	return i, err
}

const getMiniPCIeModuleBySN = `-- name: GetMiniPCIeModuleBySN :one
select id, mini_pcie_modules_type_id, serial_number
from mini_pcie_modules
where serial_number = $1
`

type GetMiniPCIeModuleBySNRow struct {
	ID                    uuid.UUID      `json:"id"`
	MiniPcieModulesTypeID uuid.NullUUID  `json:"mini_pcie_modules_type_id"`
	SerialNumber          sql.NullString `json:"serial_number"`
}

func (q *Queries) GetMiniPCIeModuleBySN(ctx context.Context, serialNumber sql.NullString) (GetMiniPCIeModuleBySNRow, error) {
	row := q.db.QueryRowContext(ctx, getMiniPCIeModuleBySN, serialNumber)
	var i GetMiniPCIeModuleBySNRow
	err := row.Scan(&i.ID, &i.MiniPcieModulesTypeID, &i.SerialNumber)
	return i, err
}
