// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: miniPCeModules.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createMiniPCeModule = `-- name: CreateMiniPCeModule :one
INSERT INTO mini_pcie_modules (mini_pcie_modules_type_id, serial_number)
VALUES ($1, $2)
RETURNING id, mini_pcie_modules_type_id, serial_number, created_at, updated_at, is_deleted
`

type CreateMiniPCeModuleParams struct {
	MiniPcieModulesTypeID uuid.NullUUID  `json:"mini_pcie_modules_type_id"`
	SerialNumber          sql.NullString `json:"serial_number"`
}

func (q *Queries) CreateMiniPCeModule(ctx context.Context, arg CreateMiniPCeModuleParams) (MiniPcieModule, error) {
	row := q.db.QueryRowContext(ctx, createMiniPCeModule, arg.MiniPcieModulesTypeID, arg.SerialNumber)
	var i MiniPcieModule
	err := row.Scan(
		&i.ID,
		&i.MiniPcieModulesTypeID,
		&i.SerialNumber,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsDeleted,
	)
	return i, err
}

const getAllMiniPCeModules = `-- name: GetAllMiniPCeModules :many
SELECT mpt.name as name,
       m.id, m.mini_pcie_modules_type_id, m.serial_number, m.created_at, m.updated_at, m.is_deleted
FROM mini_pcie_modules m
         LEFT JOIN mini_pcie_modules_type mpt ON mpt.id = m.mini_pcie_modules_type_id
`

type GetAllMiniPCeModulesRow struct {
	Name                  sql.NullString `json:"name"`
	ID                    uuid.UUID      `json:"id"`
	MiniPcieModulesTypeID uuid.NullUUID  `json:"mini_pcie_modules_type_id"`
	SerialNumber          sql.NullString `json:"serial_number"`
	CreatedAt             sql.NullTime   `json:"created_at"`
	UpdatedAt             sql.NullTime   `json:"updated_at"`
	IsDeleted             sql.NullBool   `json:"is_deleted"`
}

func (q *Queries) GetAllMiniPCeModules(ctx context.Context) ([]GetAllMiniPCeModulesRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllMiniPCeModules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllMiniPCeModulesRow
	for rows.Next() {
		var i GetAllMiniPCeModulesRow
		if err := rows.Scan(
			&i.Name,
			&i.ID,
			&i.MiniPcieModulesTypeID,
			&i.SerialNumber,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsDeleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllMiniPCeModulesType = `-- name: GetAllMiniPCeModulesType :many
SELECT id, name, module_type_number, created_at, updated_at, is_deleted
FROM mini_pcie_modules_type
`

func (q *Queries) GetAllMiniPCeModulesType(ctx context.Context) ([]MiniPcieModulesType, error) {
	rows, err := q.db.QueryContext(ctx, getAllMiniPCeModulesType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MiniPcieModulesType
	for rows.Next() {
		var i MiniPcieModulesType
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ModuleTypeNumber,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsDeleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMiniPCeModuleById = `-- name: GetMiniPCeModuleById :one
SELECT mpt.name as name,
       m.id, m.mini_pcie_modules_type_id, m.serial_number, m.created_at, m.updated_at, m.is_deleted
FROM mini_pcie_modules m
         LEFT JOIN mini_pcie_modules_type mpt ON mpt.id = m.mini_pcie_modules_type_id
WHERE m.id = $1
`

type GetMiniPCeModuleByIdRow struct {
	Name                  sql.NullString `json:"name"`
	ID                    uuid.UUID      `json:"id"`
	MiniPcieModulesTypeID uuid.NullUUID  `json:"mini_pcie_modules_type_id"`
	SerialNumber          sql.NullString `json:"serial_number"`
	CreatedAt             sql.NullTime   `json:"created_at"`
	UpdatedAt             sql.NullTime   `json:"updated_at"`
	IsDeleted             sql.NullBool   `json:"is_deleted"`
}

func (q *Queries) GetMiniPCeModuleById(ctx context.Context, id uuid.UUID) (GetMiniPCeModuleByIdRow, error) {
	row := q.db.QueryRowContext(ctx, getMiniPCeModuleById, id)
	var i GetMiniPCeModuleByIdRow
	err := row.Scan(
		&i.Name,
		&i.ID,
		&i.MiniPcieModulesTypeID,
		&i.SerialNumber,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsDeleted,
	)
	return i, err
}
